# Generated by Django 4.2.4 on 2024-02-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main5', '0003_alter_product_options_alter_product_create_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_stoc',
            new_name='in_stock',
        ),
    ]
